// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeReporter.Models;

#nullable disable

namespace TimeReporter.Migrations
{
    [DbContext(typeof(TimeReporterContext))]
    [Migration("20211227131449_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TimeReporter.Models.Accepted", b =>
                {
                    b.Property<int>("AcceptedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("AcceptedId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ReportId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Accepteds");

                    b.HasData(
                        new
                        {
                            AcceptedId = 1,
                            ActivityId = 2,
                            ReportId = 1,
                            Time = 50,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            AcceptedId = 2,
                            ActivityId = 7,
                            ReportId = 1,
                            Time = 110,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            AcceptedId = 3,
                            ActivityId = 3,
                            ReportId = 1,
                            Time = 25,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            AcceptedId = 4,
                            ActivityId = 2,
                            ReportId = 4,
                            Time = 70,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            AcceptedId = 5,
                            ActivityId = 8,
                            ReportId = 4,
                            Time = 100,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            AcceptedId = 6,
                            ActivityId = 7,
                            ReportId = 4,
                            Time = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            AcceptedId = 7,
                            ActivityId = 5,
                            ReportId = 4,
                            Time = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            AcceptedId = 8,
                            ActivityId = 3,
                            ReportId = 8,
                            Time = 70,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 8
                        },
                        new
                        {
                            AcceptedId = 9,
                            ActivityId = 1,
                            ReportId = 8,
                            Time = 100,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 8
                        });
                });

            modelBuilder.Entity("TimeReporter.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("ActivityId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            Active = false,
                            Budget = 115,
                            Code = "Mercury-1",
                            Name = "Mercury",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            ActivityId = 2,
                            Active = true,
                            Budget = 50,
                            Code = "Jupiter-2",
                            Name = "Jupiter",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            ActivityId = 3,
                            Active = true,
                            Budget = 100,
                            Code = "Pluto-1",
                            Name = "Pluto",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            ActivityId = 4,
                            Active = true,
                            Budget = 100,
                            Code = "Saturn-5",
                            Name = "Saturn",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            ActivityId = 5,
                            Active = true,
                            Budget = -10,
                            Code = "Venus-3",
                            Name = "Venus",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 5
                        },
                        new
                        {
                            ActivityId = 6,
                            Active = true,
                            Budget = 70,
                            Code = "Uranus-2",
                            Name = "Uranus",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 6
                        },
                        new
                        {
                            ActivityId = 7,
                            Active = true,
                            Budget = -1,
                            Code = "OTHER",
                            Name = "Other",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 7
                        },
                        new
                        {
                            ActivityId = 8,
                            Active = false,
                            Budget = 150,
                            Code = "Neptune-7",
                            Name = "Neptune",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 8
                        },
                        new
                        {
                            ActivityId = 9,
                            Active = true,
                            Budget = 150,
                            Code = "Luna-1",
                            Name = "Luna",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 9
                        },
                        new
                        {
                            ActivityId = 10,
                            Active = true,
                            Budget = 300,
                            Code = "Europa-77",
                            Name = "Europa",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 10
                        });
                });

            modelBuilder.Entity("TimeReporter.Models.Entry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int?>("SubactivityId")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("EntryId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ReportId");

                    b.HasIndex("SubactivityId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            EntryId = 1,
                            ActivityId = 2,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "created view",
                            ReportId = 1,
                            SubactivityId = 5,
                            Time = 70,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            EntryId = 2,
                            ActivityId = 7,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "tea time",
                            ReportId = 1,
                            Time = 150,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            EntryId = 3,
                            ActivityId = 3,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "edited model",
                            ReportId = 1,
                            SubactivityId = 9,
                            Time = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            EntryId = 4,
                            ActivityId = 2,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "edited row",
                            ReportId = 4,
                            SubactivityId = 4,
                            Time = 70,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            EntryId = 5,
                            ActivityId = 8,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "added button",
                            ReportId = 4,
                            SubactivityId = 23,
                            Time = 150,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            EntryId = 6,
                            ActivityId = 7,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "resting",
                            ReportId = 4,
                            Time = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            EntryId = 7,
                            ActivityId = 5,
                            Date = new DateTime(2021, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "modified controller",
                            ReportId = 4,
                            SubactivityId = 15,
                            Time = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            EntryId = 8,
                            ActivityId = 5,
                            Date = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "created view",
                            ReportId = 4,
                            SubactivityId = 14,
                            Time = 150,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            EntryId = 9,
                            ActivityId = 3,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "created table",
                            ReportId = 8,
                            SubactivityId = 7,
                            Time = 70,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 8
                        },
                        new
                        {
                            EntryId = 10,
                            ActivityId = 1,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "modified view",
                            ReportId = 8,
                            SubactivityId = 2,
                            Time = 120,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 8
                        },
                        new
                        {
                            EntryId = 11,
                            ActivityId = 8,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "tea time",
                            ReportId = 10,
                            Time = 15,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 10
                        },
                        new
                        {
                            EntryId = 12,
                            ActivityId = 2,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "celebrating",
                            ReportId = 10,
                            Time = 30,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 10
                        },
                        new
                        {
                            EntryId = 13,
                            ActivityId = 9,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "added view",
                            ReportId = 10,
                            SubactivityId = 26,
                            Time = 130,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 10
                        },
                        new
                        {
                            EntryId = 14,
                            ActivityId = 1,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "modified view",
                            ReportId = 10,
                            SubactivityId = 2,
                            Time = 80,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 10
                        },
                        new
                        {
                            EntryId = 15,
                            ActivityId = 9,
                            Date = new DateTime(2021, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "tea time",
                            ReportId = 10,
                            Time = 25,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 10
                        });
                });

            modelBuilder.Entity("TimeReporter.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Frozen")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = true,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            ReportId = 2,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = false,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            ReportId = 3,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = false,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            ReportId = 4,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = true,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            ReportId = 5,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = false,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 5
                        },
                        new
                        {
                            ReportId = 6,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = false,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 6
                        },
                        new
                        {
                            ReportId = 7,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = false,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 7
                        },
                        new
                        {
                            ReportId = 8,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = true,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 8
                        },
                        new
                        {
                            ReportId = 9,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = false,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 9
                        },
                        new
                        {
                            ReportId = 10,
                            Date = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Frozen = false,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 10
                        });
                });

            modelBuilder.Entity("TimeReporter.Models.Subactivity", b =>
                {
                    b.Property<int>("SubactivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("SubactivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("Subactivities");

                    b.HasData(
                        new
                        {
                            SubactivityId = 1,
                            ActivityId = 1,
                            Code = "database",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 2,
                            ActivityId = 1,
                            Code = "frontend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 3,
                            ActivityId = 1,
                            Code = "backend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 4,
                            ActivityId = 2,
                            Code = "database",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 5,
                            ActivityId = 2,
                            Code = "frontend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 6,
                            ActivityId = 2,
                            Code = "backend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 7,
                            ActivityId = 3,
                            Code = "database",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 8,
                            ActivityId = 3,
                            Code = "frontend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 9,
                            ActivityId = 3,
                            Code = "backend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 10,
                            ActivityId = 4,
                            Code = "database",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 11,
                            ActivityId = 4,
                            Code = "frontend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 12,
                            ActivityId = 4,
                            Code = "backend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 13,
                            ActivityId = 5,
                            Code = "database",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 14,
                            ActivityId = 5,
                            Code = "frontend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 15,
                            ActivityId = 5,
                            Code = "backend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 16,
                            ActivityId = 6,
                            Code = "database",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 17,
                            ActivityId = 6,
                            Code = "frontend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 18,
                            ActivityId = 6,
                            Code = "backend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 22,
                            ActivityId = 8,
                            Code = "database",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 23,
                            ActivityId = 8,
                            Code = "frontend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 24,
                            ActivityId = 8,
                            Code = "backend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 25,
                            ActivityId = 9,
                            Code = "database",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 26,
                            ActivityId = 9,
                            Code = "frontend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 27,
                            ActivityId = 9,
                            Code = "backend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 28,
                            ActivityId = 10,
                            Code = "database",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 29,
                            ActivityId = 10,
                            Code = "frontend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubactivityId = 30,
                            ActivityId = 10,
                            Code = "backend",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TimeReporter.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            WorkerId = 1,
                            Name = "Clarkson",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 2,
                            Name = "Hammond",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 3,
                            Name = "May",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 4,
                            Name = "Plant",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 5,
                            Name = "Page",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 6,
                            Name = "Bonham",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 7,
                            Name = "Jones",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 8,
                            Name = "Hetfield",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 9,
                            Name = "Hammett",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 10,
                            Name = "Ulrich",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkerId = 11,
                            Name = "Trujillo",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TimeReporter.Models.Accepted", b =>
                {
                    b.HasOne("TimeReporter.Models.Activity", "Activity")
                        .WithMany("Accepteds")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeReporter.Models.Report", "Report")
                        .WithMany("Accepteds")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeReporter.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Report");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("TimeReporter.Models.Activity", b =>
                {
                    b.HasOne("TimeReporter.Models.Worker", "Worker")
                        .WithMany("Activities")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("TimeReporter.Models.Entry", b =>
                {
                    b.HasOne("TimeReporter.Models.Activity", "Activity")
                        .WithMany("Entries")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeReporter.Models.Report", "Report")
                        .WithMany("Entries")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeReporter.Models.Subactivity", "Subactivity")
                        .WithMany("Entries")
                        .HasForeignKey("SubactivityId");

                    b.HasOne("TimeReporter.Models.Worker", "Worker")
                        .WithMany("Entries")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Report");

                    b.Navigation("Subactivity");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("TimeReporter.Models.Report", b =>
                {
                    b.HasOne("TimeReporter.Models.Worker", "Worker")
                        .WithMany("Reports")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("TimeReporter.Models.Subactivity", b =>
                {
                    b.HasOne("TimeReporter.Models.Activity", "Activity")
                        .WithMany("Subactivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("TimeReporter.Models.Activity", b =>
                {
                    b.Navigation("Accepteds");

                    b.Navigation("Entries");

                    b.Navigation("Subactivities");
                });

            modelBuilder.Entity("TimeReporter.Models.Report", b =>
                {
                    b.Navigation("Accepteds");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("TimeReporter.Models.Subactivity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("TimeReporter.Models.Worker", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Entries");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
